services:
  dark:
    image: tugboatqa/php:7-apache
    default: true
    depends: light
    commands:
      build:
        - ln -snf $TUGBOAT_ROOT/dark $DOCROOT
  light:
    image: tugboatqa/php:7-apache
    expose: 80
    checkout: true
    commands:
      build:
        - ln -snf $TUGBOAT_ROOT/light $DOCROOT
